package rtepub

const (
	SNIPPET_START_EVENT   = "SNIPPET_START"
	SNIPPET_RUNNING_EVENT = "SNIPPET_RUNNING"
	SNIPPET_STOP_EVENT    = "SNIPPET_STOP"
	SNIPPET_OUTPUT_EVENT  = "SNIPPET_OUTPUT"
)
const (
	Lua = "lua"
	R   = "r"
)

const (
	STATE_CREATE_FAILED     = "STATE_CREATE_FAILED"
	SNIPPET_OUT_OF_MEMORY   = "OUT_OF_MEMORY"
	SNIPPET_CODE_GET_FAILED = "CODE_GET_FAILED"
	SNIPPET_REPL_FAILED     = "REPL_FAILED"
	SNIPPET_RUN_FINISHED    = "FINISHED"
	SNIPPET_RUN_TIMEDOUT    = "TIMED_OUT"
	START_MONITORING_FAILED = "START_MONITORING_FAILED"

	SNIPPET_RUN_TIMEDOUT_DESCR  = "snippet execution deadline exceeded"
	SNIPPET_OUT_OF_MEMORY_DESCR = "snippet has run out of memory"
)
